// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6O23AUNg1cn43veboDtBknzLRULgfnpE',
    appId: '1:547142197260:web:51003f3e33266da5724e29',
    messagingSenderId: '547142197260',
    projectId: 'fluttertp-cf1d4',
    authDomain: 'fluttertp-cf1d4.firebaseapp.com',
    storageBucket: 'fluttertp-cf1d4.firebasestorage.app',
    measurementId: 'G-WZ4J9P2CEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6V5aZl-god7ocmhmZvMiuauqRM9JCufw',
    appId: '1:547142197260:android:95b0f816378d56e9724e29',
    messagingSenderId: '547142197260',
    projectId: 'fluttertp-cf1d4',
    storageBucket: 'fluttertp-cf1d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa6MCnktxTQnrF6Qm-3AYDfNz6aGicTwI',
    appId: '1:547142197260:ios:49ef1e7cf5bbec1e724e29',
    messagingSenderId: '547142197260',
    projectId: 'fluttertp-cf1d4',
    storageBucket: 'fluttertp-cf1d4.firebasestorage.app',
    iosBundleId: 'com.example.tp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa6MCnktxTQnrF6Qm-3AYDfNz6aGicTwI',
    appId: '1:547142197260:ios:49ef1e7cf5bbec1e724e29',
    messagingSenderId: '547142197260',
    projectId: 'fluttertp-cf1d4',
    storageBucket: 'fluttertp-cf1d4.firebasestorage.app',
    iosBundleId: 'com.example.tp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6O23AUNg1cn43veboDtBknzLRULgfnpE',
    appId: '1:547142197260:web:8104c6a717d7e606724e29',
    messagingSenderId: '547142197260',
    projectId: 'fluttertp-cf1d4',
    authDomain: 'fluttertp-cf1d4.firebaseapp.com',
    storageBucket: 'fluttertp-cf1d4.firebasestorage.app',
    measurementId: 'G-4HC221X1HV',
  );
}
